@host = http://localhost:3000

### get all boards
GET {{host}}/boards HTTP/1.1

### create board
POST {{host}}/boards HTTP/1.1
Content-Type: application/json

{
  "title": "새로운 글",
  "content": "새로운 글 내용입니다."
}
