@host=http://localhost:3000

### create user
POST {{host}}/user/create HTTP/1.1
Content-Type: application/json

{
  "username": "윤지원",
  "password": "1212",
  "email": "jiwon@test.com"    
}

### get user
GET {{host}}/user/getUser/kenux@test.com HTTP/1.1

###
GET {{host}}/user HTTP/1.1


### update user
PUT {{host}}/user/update/kenux@test.com HTTP/1.1
Content-Type: application/json

{
  "username": "kenux2",
  "password": "1313",
  "email": "kenux@test.com"    
}

### delete user
DELETE {{host}}/user/delete/kenux@test.com HTTP/1.1

### auth - register
POST {{host}}/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "kenux11@test.com",
  "username": "kenux11",
  "password": "1212"
}
